[package]
name = "rusty-sailor"
version = "0.0.1"
authors = ["Aleksander Gondek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
config = { version = "0.10.1", features = ["ini"] }
