# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
 
  
  config.vm.network "private_network", ip: "192.168.99.10"
  config.vm.synced_folder "../target/release", "/vagrant_data"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
