# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  config.vm.network "private_network", ip: "192.168.99.12"
  config.vm.synced_folder "../", "/vagrant_data"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y git

    cd /home/vagrant
    git clone git://git.musl-libc.org/musl
    cd /home/vagrant/musl
    ./configure
    make
    sudo make install

    echo 'export PATH=${PATH}:/usr/local/musl/bin' >> /home/vagrant/.bashrc
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source /home/vagrant/.cargo/env
    rustup target add x86_64-unknown-linux-musl
  SHELL
end
